### ISSUE TITLE
如何配置postgresql?

### ISSUE THREAD

**Issue by haiiv** [ctripcorp/SQLlin#3]
您好，我看文档中是本地数据库的配置方法，如何配置postgresql数据库呢？

**Comment by qiaoyuang** [comment]
SQLlin 目前侧重于在客户端开发中支持 Kotlin Multiplatform 调用 SQLite，在 JVM 后端场景中使用 JDBC 连接后端数据库还暂时不支持。

**Comment by haiiv** [comment]
好的，希望后续支持，谢谢乔老师。

> SQLlin 目前侧重于在客户端开发中支持 Kotlin Multiplatform 调用 SQLite，在 JVM 后端场景中使用 JDBC 连接后端数据库还暂时不支持。

**Comment by qiaoyuang** [comment]
> 

客气了，等 SQLlin 在客户端开发中功能更完善之后，我会考虑下 JVM 后端的场景。
