### ISSUE TITLE
Native driver does not respect isReadOnly

### ISSUE THREAD

**Issue by nbransby** [ctripcorp/SQLlin#50]
Calling openDatabase with isReadOnly = true should use the [SQLITE_OPEN_READONLY](https://stackoverflow.com/a/5485634/737857) flag in [NativeDatabase.openNativeDatabase](https://github.com/ctripcorp/SQLlin/blob/0e5546d14a27fdaee325245c29449388749ed9db/sqllin-driver/src/nativeMain/kotlin/com/ctrip/sqllin/driver/cinterop/NativeDatabase.kt#L48C43-L48C43)

**Comment by qiaoyuang** [comment]
This is a known problem. This design cause I want to keep consistency with the implementation on Android. The implementation of sqllin-driver on Android base on [SQLiteOpenHelper](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper). When you call [SQLiteOpenHelper.getReadableDatabase](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper#getReadableDatabase()), most of time you still would get a writable database. But, obviously, the property `isReadyOnly` still has slightly different behavior between Android and Native platforms now, I would like to find a better way to solve this problem in the future.

**Comment by nbransby** [comment]
Strange the [docs for SQLITE_OPEN_READWRITE](https://www.sqlite.org/c3ref/open.html) state "For historical reasons, if opening in read-write mode fails due to OS-level permissions, an attempt is made to open it in read-only mode"

But that's not what we are seeing when opening a sqlite file from the main bundle (obviously read-only), we get `Uncaught Kotlin exception: com.ctrip.sqllin.driver.SQLiteException: Could not open the database in read/write mode
`

**Comment by nbransby** [comment]
I assume its because `SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE` is used and that does not attempt the read-only mode

**Comment by qiaoyuang** [comment]
OK, I understand your situation. I will add the logic that use `SQLITE_READ_ONLY` to retry when `SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE` fails on native platforms.

**Comment by nbransby** [comment]
Yes or maybe the other way round: https://github.com/ctripcorp/SQLlin/pull/51/files

As the first call should only fail once for databases that need to be created whilst the other way round the first call will always fail for databases in readonly storage

**Comment by nbransby** [comment]
Updated the PR to also avoid the internal retry in sqlite ""For historical reasons, if opening in read-write mode fails due to OS-level permissions, an attempt is made to open it in read-only mode" if isReadOnly

**Comment by qiaoyuang** [comment]
I proposed some questions in your PR flow. We can discuss in there.

**Comment by qiaoyuang** [comment]
@nbransby Hi, SQLlin `1.2.1` has been published to MavenCentral. You can try it now.

**Comment by nbransby** [comment]
Thanks @qiaoyuang will confirm it works once tested
