### ISSUE TITLE
Uncaught Kotlin exception: com.ctrip.sqllin.driver.SQLiteResultCode: error rawExecSql: PRAGMA user_version = 1;, attempt to write a readonly database | error code SQLITE_READONLY

### ISSUE THREAD

**Issue by nbransby** [ctripcorp/SQLlin#53]
Got a new issue now - are you calling  PRAGMA user_version = 1 internally in SQLlin somewhere?

**Comment by nbransby** [comment]
im guessing its here https://github.com/ctripcorp/SQLlin/blob/776e1f995259e36086d97bc4c578cf17ad9ca006/sqllin-driver/src/commonMain/kotlin/com/ctrip/sqllin/driver/Extension.kt#L99C1-L100C1

**Comment by nbransby** [comment]
And then thrown from here https://github.com/ctripcorp/SQLlin/blob/776e1f995259e36086d97bc4c578cf17ad9ca006/sqllin-driver/src/nativeMain/kotlin/com/ctrip/sqllin/driver/ExtensionNative.kt#L46

**Comment by qiaoyuang** [comment]
Okay, I will look at this issue today.

**Comment by qiaoyuang** [comment]
Before I fix it, you can keep the property `DatabaseConfiguration.version` same with in your database file on read-only mode.

**Comment by qiaoyuang** [comment]
I think this is a reasonable behavior. If users use read-only mode, they should ensure the value of `DatabaseConfiguration.version` same with the value in database file. So, I would add a separate check for this situation and throw an `IllegalArgumentException` with the related message.

**Comment by nbransby** [comment]
Does that number have to be greater than 0?

**Comment by qiaoyuang** [comment]
Yes, if we create a new database, usually set the version is 1.

**Comment by nbransby** [comment]
OK great thanks
