### ISSUE TITLE
（Feature Request）有计划提供执行原生sql的api吗？

### ISSUE THREAD

**Issue by selcarpa** [ctripcorp/SQLlin#62]
![image](https://github.com/ctripcorp/SQLlin/assets/25505798/6b1bff77-cde5-48ef-85f7-d700a2563eb2)

将所有的sql语句dsl化可能有点耗时间，但有没有计划提供类似这种形式直接执行sql的方式（并提供事务支持）。

[完整代码](https://github.com/selcarpa/lurker/blob/d310bd8c98d22c688ed075e500d5aef5718d1979/src/commonMain/kotlin/database/model/DomainRecord.kt#L40-L56)

**Comment by qiaoyuang** [comment]
可以直接使用 sqllin-driver，详见 sqllin-driver 的 [README](https://github.com/ctripcorp/SQLlin/blob/main/sqllin-driver/README_CN.md)

**Comment by selcarpa** [comment]
看这份README中说不建议直接使用，虽然我确实是直接使用的，因为openDatabase最终还是返回的一个DatabaseConnection。
我暂时没有详细阅读源码，不确定这种方式是否能同步使用sqllin dsl的事务呢？

**Comment by qiaoyuang** [comment]
可以，有 driver 级别的 transaction API。我写不建议使用主要是因为有 sqllin-dsl 的存在，大多数时候没有必要直接使用 sqllin-driver

**Comment by selcarpa** [comment]
好的，感谢，希望也添加一下相关说明。

**Comment by qiaoyuang** [comment]
哪部分的说明？driver 层详细的 API 使用文档吗

**Comment by selcarpa** [comment]
对的，包含刚才提到的是否有事务之类的

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by qiaoyuang** [comment]
可以，有空的时候我可以再添加一些内容。其实 transaction 属于 SQLite 的能力，sqllin-driver 拥有完整的 SQLite 能力，sqllin-dsl 只是在其之上实现了 SQL 语句的 DSL 化，sqllin-dsl 不会包含任何底层 SQLite API 级别的实现。
