### ISSUE TITLE
Update Kotlin version: 1.9.20 -> 1.9.21

### ISSUE THREAD

**Issue by ddolovov** [ctripcorp/SQLlin#64]
Dear Library Maintainer,

We have just released Kotlin 1.9.21 that fixes critical issue that, in some cases, resulted in the production of incorrect klib libraries. Details: `https://youtrack.jetbrains.com/issue/KT-62515`. We have detected that there are libraries built with 1.9.20 that were published to Maven Central. And these libraries are affected by the issue:

com.ctrip.kotlin:sqllin-driver:1.2.2
com.ctrip.kotlin:sqllin-dsl:1.2.2

We highly recommend you rebuilding these libraries with 1.9.21 and republishing them to minimize possible negative impact. Please take our apologies for this inconvenience. We will take the necessary measures to avoid similar issues in the future.

Kotlin Team.

**Comment by qiaoyuang** [comment]
Done. I have published the version `1.2.3`. It has updated Kotlin version to `1.9.21`.
