### ISSUE TITLE
自增主键ID问题

### ISSUE THREAD

**Issue by jiangkaifang** [ctripcorp/SQLlin#68]
您好！
    我想问一下，如果我创建的表中包含自增键（比如说字段名叫 id），那么我对应表的实体类需要应该怎么来创建？如果实体类加入了 id 这个属性，那么在执行insert的时候就会出问题，如果实体类不加入 id 这个属性，那么我在select的时候应该怎么来取得这个 id 的值呢

**Comment by qiaoyuang** [comment]
你说的这个场景确实是个问题，目前你可以定义两个 data class，一个专门用来 insert，一个专门用来 select，用于暂时应对这个场景。至于长期的解决方案，我倾向于使用注解的方式，后续有进展我会同步给你。

**Comment by jiangkaifang** [comment]
好的，谢谢你的回复，我已经知道该怎么做了
