### ISSUE TITLE
我按照说明文档一步一步进行，但无法正常使用

### ISSUE THREAD

**Issue by Matcha-xiaobin** [ctripcorp/SQLlin#69]
我仔细按照教程 开始使用 一步一步进行
我给我的实体类加上了DBRow
![image](https://github.com/ctripcorp/SQLlin/assets/5775066/44da1cff-b1f1-4f83-8e16-9040695f1457)

但是我无法找到这个类对应的表
![image](https://github.com/ctripcorp/SQLlin/assets/5775066/799d28e6-ba6b-4437-bb42-dd361cc8ee43)
![image](https://github.com/ctripcorp/SQLlin/assets/5775066/dbc80c72-dfea-48d0-be6c-72325062e1ad)

是什么地方缺少了什么吗？

**Comment by qiaoyuang** [comment]
这个表存在吗，不存在的话你要用 SQL 语句建表

**Comment by qiaoyuang** [comment]
看看 build.gradle.kts 中你对 sqllin-processor 的依赖

**Comment by Matcha-xiaobin** [comment]
![image](https://github.com/ctripcorp/SQLlin/assets/5775066/7913df1e-d302-4fbd-838c-be990e933e91)
因为用不了，暂时先注释掉了

用sql语句建表是指什么？文档中并未详细说明，所以我不太明白

**Comment by Matcha-xiaobin** [comment]
![Uploading image.png…]()

**Comment by qiaoyuang** [comment]
SQL 语句建表那个忽略，我刚才看错了。其实你的问题是 KSP 生成的 Table 对象找不到，我现在在火车上不方便，等明天我给你看下。

**Comment by Matcha-xiaobin** [comment]
好的，顺便有劳大佬看下这个问题：
![image](https://github.com/ctripcorp/SQLlin/assets/5775066/72b9c7a4-0f88-499f-a7e7-c894fca5abbd)
不知道如何解决

**Comment by qiaoyuang** [comment]
这个问题跟 SQLlin 无关吧？只有这些报错信息我也不知道该如何解决。你可以在 YouTrack 上搜索相关关键字或者提问，JetBrains 官方的人应该可以帮助你。

**Comment by Matcha-xiaobin** [comment]
> 这个问题跟 SQLlin 无关吧？只有这些报错信息我也不知道该如何解决。你可以在 YouTrack 上搜索相关关键字或者提问，JetBrains 官方的人应该可以帮助你。

因为我这边看了下我只是加入了SQLlin 就出现了这个问题，所以就觉得可能是这个导致的，我自己又研究了下，似乎是KSP的问题。先不管这个了，不影响运行。

**Comment by qiaoyuang** [comment]
你检查一下这行代码在不在你的 build.gradle.kts 里：

```
kotlin.srcDir("build/generated/ksp/metadata/commonMain/kotlin")
```

如果在的话，你完整 build 一次看看你的这个路径下有没有 Table 类生成

**Comment by Matcha-xiaobin** [comment]
> 你检查一下这行代码在不在你的 build.gradle.kts 里：
> 
> ```
> kotlin.srcDir("build/generated/ksp/metadata/commonMain/kotlin")
> ```
> 
> 如果在的话，你完整 build 一次看看你的这个路径下有没有 Table 类生成

这行代码在的，但是没有生成ksp这个路径

**Comment by Matcha-xiaobin** [comment]
![image](https://github.com/ctripcorp/SQLlin/assets/5775066/9bf99e93-0d42-42ef-a54d-5f0b6db14e0d)

**Comment by Matcha-xiaobin** [comment]
![image](https://github.com/ctripcorp/SQLlin/assets/5775066/f495ff55-886b-4c06-9cbb-b2ad49d6898c)
![image](https://github.com/ctripcorp/SQLlin/assets/5775066/bd00253e-2976-4f9d-914a-49567876ae48)
![image](https://github.com/ctripcorp/SQLlin/assets/5775066/b27c6fde-f7da-410c-bb1e-497284039bb8)
![image](https://github.com/ctripcorp/SQLlin/assets/5775066/4a71c196-206f-4911-8135-ccb9af67b08f)
这是我的相关配置，有劳大佬看下。
sqllin 是 1.2.3，放在了 commonMain 里

**Comment by Matcha-xiaobin** [comment]
ksp我记得我是尝试过1.9.21 版本，结果是一样的

**Comment by qiaoyuang** [comment]
在确保 Kotlin 1.9.21，KSP 版本 1.9.21-1.0.15 的情况下也会出现问题吗？我看你注释掉的 KSP 版本是 1.9.21-1.0.16

**Comment by Matcha-xiaobin** [comment]
> 在确保 Kotlin 1.9.21，KSP 版本 1.9.21-1.0.15 的情况下也会出现问题吗？我看你注释掉的 KSP 版本是 1.9.21-1.0.16

尝试过1.9.21-1.0.15，没用

**Comment by qiaoyuang** [comment]
那仅从这些信息我已经看不出问题了，你能否提供一个可以复现该问题的最小 demo 工程？

**Comment by Matcha-xiaobin** [comment]
[Demo.zip](https://github.com/ctripcorp/SQLlin/files/13807127/Demo.zip)
这是demo，你可以看下

**Comment by qiaoyuang** [comment]
我尝试了以下几处更改，目前已经可以生成 `BrowsingHistoryBeanTable` 类。具体做法如下你可以尝试：

- 1. 所有 Java 版本的设置从 18 改成 17，Java 18 为非长期支持版本，社区生态在支持方面不如长期支持版本。
- 2. _sqllin-processor_ 的版本设置上从 libs 的写法改成直接写数字（我本地用你的写法会 build 报错）
- 3. 在 shared module 的 `build.gradle.kts` 中添加如下代码（`dependencies {}` 块下方的代码）：

```
// KSP dependencies
dependencies {
    // sqllin-processor
    add("kspCommonMainMetadata", "com.ctrip.kotlin:sqllin-processor:1.2.3")
}

afterEvaluate {  // WORKAROUND: both register() and named() fail – https://github.com/gradle/gradle/issues/9331
    tasks {
        withType<KotlinCompile<*>> {
            if (name != "kspCommonMainKotlinMetadata")
                dependsOn("kspCommonMainKotlinMetadata")
        }
    }
}
```

第 3 点是由于 Gradle 8.0 后出现了一个问题（问题链接可参照以上代码中的注释），目前社区的解决方案普遍是加以上代码来暂时规避。

**Comment by Matcha-xiaobin** [comment]
> 我尝试了以下几处更改，目前已经可以生成 `BrowsingHistoryBeanTable` 类。具体做法如下你可以尝试：
> 
> * 1. 所有 Java 版本的设置从 18 改成 17，Java 18 为非长期支持版本，社区生态在支持方面不如长期支持版本。
> * 2. _sqllin-processor_ 的版本设置上从 libs 的写法改成直接写数字（我本地用你的写法会 build 报错）
> * 3. 在 shared module 的 `build.gradle.kts` 中添加如下代码（`dependencies {}` 块下方的代码）：
> 
> ```
> // KSP dependencies
> dependencies {
>     // sqllin-processor
>     add("kspCommonMainMetadata", "com.ctrip.kotlin:sqllin-processor:1.2.3")
> }
> 
> afterEvaluate {  // WORKAROUND: both register() and named() fail – https://github.com/gradle/gradle/issues/9331
>     tasks {
>         withType<KotlinCompile<*>> {
>             if (name != "kspCommonMainKotlinMetadata")
>                 dependsOn("kspCommonMainKotlinMetadata")
>         }
>     }
> }
> ```
> 
> 第 3 点是由于 Gradle 8.0 后出现了一个问题（问题链接可参照以上代码中的注释），目前社区的解决方案普遍是加以上代码来暂时规避。

好的，非常感谢，我稍后尝试一下！

**Comment by Matcha-xiaobin** [comment]
@qiaoyuang 试了下，确实可以生成了，感谢！
