### ISSUE TITLE
关于实体类里的字段数量不能比表中的列数多的问题

### ISSUE THREAD

**Issue by Matcha-xiaobin** [ctripcorp/SQLlin#73]
可否根据是否有@Transient 注解来判断是否需要在表中创建这列？
有时候，部分字段并不想被写入到表，而专门为此分开写数据库专用的实体类，又觉得太麻烦了。

**Comment by qiaoyuang** [comment]
这个特性可以考虑加入计划中，后面有更新会在这里通知
