### ISSUE TITLE
'null' is not supported by default

### ISSUE THREAD

**Issue by Deorigami** [ctripcorp/SQLlin#81]
'null' is not supported by default
I created a Data Class with nullable value, but when i insert value with nullable field/properties
i got this error

kotlinx.serialization.SerializationException: 'null' is not supported by default

![gambar](https://github.com/ctripcorp/SQLlin/assets/70903634/a2cfaeb9-cf93-43a2-b6b8-8802f20dacc8)

**Comment by qiaoyuang** [comment]
Can you provide your code? The data class and the `insert` statement code.

**Comment by qiaoyuang** [comment]
This is a bug, I will fix it.

**Comment by qiaoyuang** [comment]
I have fixed it in version `1.3.1`, you can try it now.
