### ISSUE TITLE
请问SQLlin支持自连接查询吗

### ISSUE THREAD

**Issue by KailuZhang** [ctripcorp/SQLlin#99]
我需要查询单个表中code相同，但是name不同的所有数据，可以通过使用子查询和自连接的方式进行query。
比如tableName为city，使用自连接的原始SQL如下
``` sql
SELECT a.*
FROM city a
JOIN city b ON a.code = b.code
WHERE a.type = 1
  AND b.type = 1
  AND a.name <> b.name;
```
请问使用SQLlin的DSL该怎么实现呢

**Comment by qiaoyuang** [comment]
目前不支持 join 子查询，请参考文档 [高级查询](https://github.com/ctripcorp/SQLlin/issues/99)。

**Comment by KailuZhang** [comment]
高级查询中是支持JION的，但是只能JION其他表，不能JION自己

**Comment by qiaoyuang** [comment]
是的，所以我说的是”不支持 join 子查询“
